name: run-tests-on-oblig
on: [push]

jobs:
  tests:
    name: run-tests
    runs-on: windows-latest  #ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: action/checkout@v3
      - name: Setup-Python
        uses: action/setup-python@v4
        with:
          python-version: "3.10"
